import Foundation
import FoundationModels
import GameplayKit

/// A word-clue pair generated by Apple Intelligence.
@Generable
struct GeneratedWordClue: Equatable {
    @Guide(description: "A single everyday English word, 3 to 6 letters, uppercase, letters only, no proper nouns, abbreviations, or obscure crosswordese (overly specialized crossword vocabulary)")
    var word: String

    @Guide(description: "A concise crossword-style clue for the word, 2 to 8 words long, must not contain the answer word")
    var clue: String
}

/// A batch of word-clue pairs for puzzle generation.
@Generable
struct WordClueBatch: Equatable {
    @Guide(description: "A list of unique word-clue pairs for a crossword puzzle", .count(15))
    var entries: [GeneratedWordClue]
}

/// Generates word-clue pairs using Apple Intelligence on-device language model.
/// Falls back to the bundled wordlist when Apple Intelligence is unavailable.
final class AIWordService: Sendable {
    static let shared = AIWordService()

    private let fallbackService = WordListService.shared

    /// Whether Apple Intelligence is available on this device.
    var isAvailable: Bool {
        SystemLanguageModel.default.availability == .available
    }

    /// Generate a batch of word-clue pairs for a puzzle.
    /// Uses Apple Intelligence if available, otherwise falls back to bundled list.
    func generateWordClues(count: Int, maxLength: Int, seed: UInt64) async -> [WordClue] {
        guard isAvailable else {
            return fallbackWords(count: count, maxLength: maxLength, seed: seed)
        }

        do {
            let instructions = """
                You are a crossword puzzle creator. Generate unique, common English words \
                with concise crossword-style clues. Rules:
                - Words must be \(3) to \(maxLength) letters long
                - Words must be UPPERCASE, letters only (A-Z)
                - No proper nouns, no offensive words
                - Prefer everyday vocabulary that most adults and older children would know
                - Avoid obscure crosswordese, abbreviations, jargon, archaic terms, and very rare words
                - Clues must be 2-8 words, must NOT contain the answer word
                - Clues should be clever and concise, like newspaper crossword clues
                - All words must be different from each other
                - Mix word lengths: include some 3-letter, some 4-letter, some 5-letter words
                """
            let session = LanguageModelSession(instructions: instructions)

            let prompt = "Generate \(count) unique crossword word-clue pairs with words of \(3)-\(maxLength) letters using broadly familiar, everyday vocabulary."

            let response = try await session.respond(
                to: prompt,
                generating: WordClueBatch.self
            )

            let generated = response.content.entries.compactMap { entry -> WordClue? in
                let word = entry.word.uppercased().trimmingCharacters(in: .whitespacesAndNewlines)
                let clue = entry.clue.trimmingCharacters(in: .whitespacesAndNewlines)

                // Validate
                guard word.count >= 3, word.count <= maxLength,
                      word.allSatisfy({ $0.isLetter && $0.isASCII }),
                      !clue.isEmpty else {
                    return nil
                }
                return WordClue(word: word, clue: clue)
            }

            // If we got enough valid entries, use them; otherwise supplement with fallback
            if generated.count >= count / 2 {
                var results = generated
                if results.count < count {
                    let extra = fallbackWords(count: count - results.count, maxLength: maxLength, seed: seed)
                    results.append(contentsOf: extra)
                }
                return Array(results.prefix(count))
            }
        } catch {
            // AI generation failed, fall back silently
        }

        return fallbackWords(count: count, maxLength: maxLength, seed: seed)
    }

    /// Fallback: return words from the bundled wordlist.
    private func fallbackWords(count: Int, maxLength: Int, seed: UInt64) -> [WordClue] {
        let all = fallbackService.entries.filter {
            $0.word.count >= 3 && $0.word.count <= maxLength
        }
        var rng = GKMersenneTwisterRandomSource(seed: seed)
        var shuffled = all
        shuffled.shuffle(using: &rng)
        return Array(shuffled.prefix(count))
    }
}
