import Foundation
import FoundationModels
import GameplayKit
import os

private let logger = Logger(subsystem: "com.timheuer.gridlet", category: "AIWordService")

/// A word-clue pair generated by Apple Intelligence.
@Generable
struct GeneratedWordClue: Equatable {
  @Guide(
    description:
      "An English crossword answer in UPPERCASE letters only (A-Z). Must be common or recognizable, not a proper noun, abbreviation, acronym, offensive term, or obscure jargon."
  )
  var word: String

  @Guide(
    description:
      "A clever crossword-style clue, 2 to 8 words long. Must not contain the answer word or any form of it. Should read as a complete natural phrase, not a fragment. Prefer playful, indirect, figurative, conversational, or lightly witty clues. Avoid plain dictionary definitions and avoid direct imperative or infinitive clues that restate the answer as a command or simple action sentence."
  )
  var clue: String
}

@Generable
struct WordClueBatch: Equatable {
  @Guide(
    description:
      "A list of unique crossword word-clue pairs with varied word choices and no duplicate answers.",
    .count(8)
  )
  var entries: [GeneratedWordClue]
}

/// A clue rewritten by Apple Intelligence for a given crossword answer.
@Generable
struct RewrittenClue: Equatable {
  @Guide(
    description:
      "The crossword answer word in UPPERCASE letters only (A-Z). Must exactly match the provided word."
  )
  var word: String

  @Guide(
    description:
      "A clever crossword-style clue, 2 to 8 words long. Must not contain the answer word or any form of it. Should read as a complete natural phrase, not a fragment. Prefer playful, indirect, figurative, conversational, or lightly witty clues. Avoid plain dictionary definitions and avoid direct imperative or infinitive clues that restate the answer as a command or simple action sentence."
  )
  var clue: String
}

@Generable
struct RewrittenClueBatch: Equatable {
  @Guide(
    description:
      "A list of rewritten crossword clues, one per provided word. Each entry must use the exact word given.",
    .count(24)
  )
  var entries: [RewrittenClue]
}

/// Generates word-clue pairs using Apple Intelligence on-device language model.
/// Falls back to the bundled wordlist when Apple Intelligence is unavailable.
final class AIWordService: @unchecked Sendable {
  static let shared = AIWordService()

  struct GenerationResult: Sendable {
    let words: [WordClue]
    /// The set of words (uppercased) that were genuinely AI-generated (not fallback supplement).
    let aiGeneratedWords: Set<String>
    let status: AIGenerationStatus
    let detail: String?
  }

  /// Words that, when appearing last in a clue, indicate an incomplete sentence.
  /// Only includes words that are almost never valid as final words in a clue.
  private static let incompleteClueEnders: Set<String> = [
    "a", "an", "the",
    "of", "with", "into", "onto", "upon",
    "and", "or", "but", "nor",
    "is", "are", "was", "were",
    "consisting", "having", "using", "including", "containing", "composed",
  ]

  /// Number of batch requests to make to accumulate enough AI-generated entries.
  private static let batchRounds = 3

  /// Number of entries requested from each batch round.
  private static let batchEntriesPerRound = 8

  /// Minimum fraction of requested count that must pass validation to use AI output.
  private static let minimumValidFraction = 0.2

  /// Maximum time in seconds to wait for all AI batch rounds before falling back.
  static let aiTimeoutSeconds: TimeInterval = 8

  /// Recommended generation timeout by grid size. Larger grids need more candidate
  /// generation time to keep AI output in the final puzzle instead of falling back.
  static func timeoutSeconds(for gridSize: GridSize) -> TimeInterval {
    switch gridSize {
    case .five:
      return 6
    case .six:
      return 8
    case .seven:
      return 10
    }
  }

  /// Maximum time in seconds to wait for AI clue rewriting on fallback words.
  private static let clueRewriteTimeoutSeconds: TimeInterval = 10

  private let fallbackService = WordListService.shared
  private let persistence: PersistenceService
  private var crosswordGenerationPrewarmSession: LanguageModelSession?
  private var crosswordRewritePrewarmSession: LanguageModelSession?

  // MARK: - Recent word tracking

  private let recentWordsKey = "AIWordService.recentWords"
  private let recentWordsLimit = 250
  private let promptAvoidWordsLimit = 80

  private let genericWords: Set<String> = [
    "TREE", "ROCK", "THING", "ITEM", "STUFF",
  ]

  private let overusedModelFavorites: Set<String> = [
    "SPARK", "CRANE", "GLOW", "LATTE", "BREEZE", "SNEAK",
  ]

  init(persistence: PersistenceService = .shared) {
    self.persistence = persistence
  }

  /// Whether Apple Intelligence is available on this device.
  var isAvailable: Bool {
    SystemLanguageModel.default.availability == .available
  }

  /// Load the model and cache the common crossword prompt prefixes before a tap needs them.
  /// This is intentionally lightweight and safe to call from home-screen warmup.
  func prewarmCrosswordGeneration() {
    guard isAvailable else { return }
    guard crosswordGenerationPrewarmSession == nil,
      crosswordRewritePrewarmSession == nil
    else {
      return
    }

    let generationSession = LanguageModelSession(instructions: makeInstructions())
    generationSession.prewarm(
      promptPrefix: Prompt(makePromptPrefix(maxLength: GridSize.seven.dimension))
    )
    crosswordGenerationPrewarmSession = generationSession

    let rewriteSession = LanguageModelSession(instructions: makeClueRewriteInstructions())
    rewriteSession.prewarm(promptPrefix: Prompt(makeClueRewritePromptPrefix()))
    crosswordRewritePrewarmSession = rewriteSession
  }

  /// Generate a batch of word-clue pairs for a puzzle.
  /// Uses Apple Intelligence if available, otherwise falls back to bundled list.
  /// Makes multiple batch requests to accumulate enough entries.
  /// Falls back to bundled list if AI doesn't finish within the timeout.
  /// Returns the words along with generation diagnostics for developer mode.
  func generateWordClues(
    count: Int,
    maxLength: Int,
    seed: UInt64,
    timeoutSeconds: TimeInterval = aiTimeoutSeconds,
    excludedWords: Set<String> = []
  ) async -> GenerationResult {
    guard isAvailable else {
      logger.info("Apple Intelligence unavailable — using bundled fallback words")
      return GenerationResult(
        words: fallbackWords(
          count: count,
          maxLength: maxLength,
          seed: seed,
          excludedWords: excludedWords
        ),
        aiGeneratedWords: [],
        status: .appleIntelligenceUnavailable,
        detail: nil
      )
    }

    let timeoutDescription = Int(timeoutSeconds.rounded())

    do {
      return try await withThrowingTaskGroup(of: GenerationResult.self) { group in
        group.addTask {
          await self.generateWithAI(
            count: count,
            maxLength: maxLength,
            seed: seed,
            excludedWords: excludedWords
          )
        }
        group.addTask {
          try await Task.sleep(for: .seconds(timeoutSeconds))
          throw AITimeoutError()
        }

        if let result = try await group.next() {
          group.cancelAll()
          return result
        }

        return await fallbackWithAIClues(
          count: count,
          maxLength: maxLength,
          seed: seed,
          excludedWords: excludedWords,
          baseDetail: "Unexpected timeout state."
        )
      }
    } catch is AITimeoutError {
      logger.warning(
        "AI generation timed out after \(timeoutDescription)s — trying AI clue rewrite on bundled words"
      )
      return await fallbackWithAIClues(
        count: count,
        maxLength: maxLength,
        seed: seed,
        excludedWords: excludedWords,
        baseDetail: "AI generation timed out after \(timeoutDescription)s."
      )
    } catch {
      logger.error(
        "AI generation failed: \(error.localizedDescription) — trying AI clue rewrite on bundled words"
      )
      return await fallbackWithAIClues(
        count: count,
        maxLength: maxLength,
        seed: seed,
        excludedWords: excludedWords,
        baseDetail: error.localizedDescription
      )
    }
  }

  private struct AITimeoutError: Error {}

  // MARK: - AI generation

  /// The actual AI generation logic, extracted so it can be raced against a timeout.
  /// All batch rounds are launched concurrently so their inference runs in parallel,
  /// delivering roughly the latency of a single round instead of batchRounds × latency.
  private func generateWithAI(
    count: Int,
    maxLength: Int,
    seed: UInt64,
    excludedWords: Set<String> = []
  ) async
    -> GenerationResult
  {
    let recentWords = loadRecentWords()
    let solvedWords = persistence.loadSolvedWords()
    let recentWordsSet = Set(recentWords)
    let solvedWordsSet = Set(solvedWords)
    let excludedWordsSet = Set(
      excludedWords.map { $0.uppercased().trimmingCharacters(in: .whitespacesAndNewlines) }
    )
    let instructions = makeInstructions()

    // Build the avoid-words list once; all rounds share the same base list because
    // they run concurrently and cannot accumulate seen words from prior rounds.
    let baseAvoidWords = Array(
      recentWordsSet.union(solvedWordsSet).union(excludedWordsSet)
        .sorted()
        .prefix(promptAvoidWordsLimit)
    )

    var allGenerated: [WordClue] = []
    var seenWords: Set<String> = []

    // Launch all batch rounds concurrently. Use a non-throwing TaskGroup so that
    // CancellationErrors from cancelled in-flight rounds (after early exit) do not
    // propagate up and trigger the fallback path unnecessarily.
    await withTaskGroup(of: [WordClue].self) { group in
      for round in 0..<Self.batchRounds {
        group.addTask {
          do {
            try Task.checkCancellation()

            // Create a fresh session per round so context windows remain independent.
            let session = LanguageModelSession(instructions: instructions)
            let roundPrompt = self.makeRoundPrompt(
              round: round,
              maxLength: maxLength,
              avoidWords: baseAvoidWords
            )
            let response = try await session.respond(
              to: roundPrompt,
              generating: WordClueBatch.self,
              includeSchemaInPrompt: false,
              options: GenerationOptions(sampling: .greedy)
            )
            let validated = self.validateBatchEntries(
              response.content.entries,
              maxLength: maxLength,
              recentWordsSet: recentWordsSet,
              solvedWordsSet: solvedWordsSet,
              excludedWordsSet: excludedWordsSet
            )
            logger.info(
              "Round \(round + 1)/\(Self.batchRounds): AI returned \(response.content.entries.count) entries, \(validated.count) passed validation"
            )
            return validated
          } catch {
            // Cancellation (early exit after enough words) or inference failure:
            // return empty rather than propagating so other rounds can still contribute.
            if !(error is CancellationError) {
              logger.warning("Round \(round + 1) failed: \(error.localizedDescription)")
            }
            return []
          }
        }
      }

      for await roundWords in group {
        for word in roundWords {
          if !seenWords.contains(word.word) {
            seenWords.insert(word.word)
            allGenerated.append(word)
          } else {
            logger.debug("Skipping cross-round duplicate '\(word.word)'")
          }
        }
        if allGenerated.count >= count {
          group.cancelAll()
          break
        }
      }
    }

    let minimumRequired = max(Int(ceil(Double(count) * Self.minimumValidFraction)), 1)
    let aiWordSet = Set(allGenerated.map(\.word))
    logger.info(
      "AI generation complete: \(allGenerated.count) validated words (minimum required: \(minimumRequired))"
    )

    if allGenerated.count >= minimumRequired {
      appendRecentWords(allGenerated.map(\.word))

      var results = allGenerated
      let supplemented = results.count < count
      if supplemented {
        let needed = count - results.count
        let extra = fallbackWords(
          count: needed,
          maxLength: maxLength,
          seed: seed,
          excludedWords: excludedWordsSet
        )
        .filter { !seenWords.contains($0.word) }
        logger.info(
          "Supplementing with \(extra.count) bundled words (had \(results.count)/\(count) from AI)")
        results.append(contentsOf: extra)
      }

      return GenerationResult(
        words: Array(results.prefix(count)),
        aiGeneratedWords: aiWordSet,
        status: supplemented ? .generatedWithAISupplement : .generatedWithAI,
        detail: supplemented
          ? "Accepted \(allGenerated.count) validated AI entries and supplemented with bundled words."
          : "Accepted \(allGenerated.count) validated AI entries."
      )
    }

    logger.warning(
      "AI validation failed: only \(allGenerated.count) words passed (needed \(minimumRequired)) — trying AI clue rewrite on bundled words"
    )
    return await fallbackWithAIClues(
      count: count,
      maxLength: maxLength,
      seed: seed,
      excludedWords: excludedWordsSet,
      baseDetail:
        "Accepted \(allGenerated.count) validated AI entries; required at least \(minimumRequired) to use AI output."
    )
  }

  /// Validates and filters a batch of generated entries against quality and length rules.
  /// Each batch is deduplicated internally; cross-round deduplication is handled by the caller.
  private func validateBatchEntries(
    _ entries: [GeneratedWordClue],
    maxLength: Int,
    recentWordsSet: Set<String>,
    solvedWordsSet: Set<String>,
    excludedWordsSet: Set<String>
  ) -> [WordClue] {
    var batchSeen: Set<String> = []
    return entries.compactMap { entry -> WordClue? in
      let word = entry.word.uppercased().trimmingCharacters(in: .whitespacesAndNewlines)
      let clue = entry.clue.trimmingCharacters(in: .whitespacesAndNewlines)
      let clueWordCount = clue.split(whereSeparator: { $0.isWhitespace }).count

      let clueWords = Set(
        clue.uppercased()
          .components(separatedBy: .whitespacesAndNewlines)
          .map { $0.trimmingCharacters(in: .punctuationCharacters) }
          .filter { !$0.isEmpty }
      )

      if word.count < 3 || word.count > maxLength {
        logger.debug("Rejected '\(word)': length \(word.count) out of range 3-\(maxLength)")
        return nil
      }

      if !word.allSatisfy({ $0.isLetter && $0.isASCII }) {
        logger.debug("Rejected '\(word)': contains non-ASCII or non-letter characters")
        return nil
      }

      if WordSafetyFilter.isBlocked(word) {
        logger.debug("Rejected '\(word)': blocked by safety filter")
        return nil
      }

      if clue.isEmpty {
        logger.debug("Rejected '\(word)': empty clue")
        return nil
      }

      if clueWordCount < 2 || clueWordCount > 8 {
        logger.debug("Rejected '\(word)': clue '\(clue)' has \(clueWordCount) words, outside 2-8")
        return nil
      }

      if solvedWordsSet.contains(word) {
        logger.debug("Rejected '\(word)': already used in a solved puzzle")
        return nil
      }

      if excludedWordsSet.contains(word) {
        logger.debug("Rejected '\(word)': already used in a current puzzle")
        return nil
      }

      if batchSeen.contains(word) {
        logger.debug("Rejected '\(word)': duplicate word in batch")
        return nil
      }

      if Self.clueContainsAnswerOrForm(clueWords, answerWord: word) {
        logger.debug(
          "Rejected '\(word)': clue '\(clue)' contains the answer word or a form of it")
        return nil
      }

      let lastWord =
        clue
        .components(separatedBy: .whitespacesAndNewlines)
        .last?
        .lowercased()
        .trimmingCharacters(in: .punctuationCharacters) ?? ""

      if Self.incompleteClueEnders.contains(lastWord) {
        logger.debug("Rejected '\(word)': clue '\(clue)' ends with incomplete word '\(lastWord)'")
        return nil
      }

      let score = scoreCandidate(word: word, clue: clue, recentWords: recentWordsSet)
      if score < -5 {
        logger.debug("Rejected '\(word)': low novelty/quality score \(score)")
        return nil
      }

      logger.debug("Accepted '\(word)' → '\(clue)' [score: \(score)]")
      batchSeen.insert(word)
      return WordClue(word: word, clue: clue)
    }
  }

  // MARK: - Prompt building

  private func makeInstructions() -> String {
    """
    You are an expert constructor for a modern mini crossword.
    Generate common, recognizable, vivid answers that feel fair and fresh.
    Prefer short, lively words with good vowel/consonant balance and varied starting letters.
    Include some stronger anchor words, not just generic fill.
    Avoid overused crossword filler and repeated model-favorite answers.
    Keep clues playful, natural, and concise.
    For verb answers, avoid literal command-style clues like "Talk to someone." or "Ride a bike.";
    instead, clue the action indirectly through context, result, or a noun phrase.
    """
  }

  private func makePromptPrefix(maxLength: Int) -> String {
    """
    Generate \(Self.batchEntriesPerRound) crossword entries for a puzzle with answers up to \(maxLength) letters.
    Answers must be 3 to \(maxLength) letters, uppercase, unique, and common.
    Include a mix of 3-letter fill and a few 6-\(maxLength)-letter anchors.
    Favor lively, image-evoking words from different categories: actions, objects, food, weather, places, moods, travel, home life, and work life.
    Clues must be 2 to 8 words, natural-sounding, and a little indirect.
    For verb answers, do not write the clue as an imperative or infinitive sentence that simply repeats the action;
    avoid clues like "Talk to someone" or "Ride a bike" and instead describe the context, result, or situation.
    At least one third should use mild misdirection, double meaning, or light humor.
    Never include the answer or any form of it.
    """
  }

  private func makeRoundPrompt(
    round: Int,
    maxLength: Int,
    avoidWords: [String]
  ) -> String {
    let avoidLine: String
    if avoidWords.isEmpty {
      avoidLine = ""
    } else {
      avoidLine = """

        Avoid these words unless absolutely necessary:
        \(avoidWords.joined(separator: ", "))
        """
    }

    // Each round runs in parallel with the others, so we nudge each toward a
    // different semantic space to maximise variety across the combined pool.
    let categoryHint: String
    switch round {
    case 0:
      categoryHint =
        "Spread entries across actions, objects, animals, weather, and everyday life."
    case 1:
      categoryHint =
        "Focus on food, places, travel, home life, and nature."
    default:
      categoryHint =
        "Focus on emotions, personality traits, technology, work life, and school."
    }

    let letterBandHint: String
    switch round {
    case 0:
      letterBandHint = "Prefer answers starting with A, B, C, D, E, F, G, or H."
    case 1:
      letterBandHint = "Prefer answers starting with I, J, K, L, M, N, O, P, or Q."
    default:
      letterBandHint = "Prefer answers starting with R, S, T, U, V, W, X, Y, or Z."
    }

    return """
      \(makePromptPrefix(maxLength: maxLength))
      \(categoryHint)
      \(letterBandHint)
      \(avoidLine)
      """
  }

  private func makeClueRewriteInstructions() -> String {
    """
    You are an expert crossword clue writer.
    Rewrite each clue to be clever, playful, and crossword-worthy.
    Keep the exact same answer word and make each clue 2 to 8 words long.
    Prefer indirect phrasing, wordplay, and everyday language over dictionary definitions.
    For verb answers, avoid direct command-style clues and simple action sentences.
    """
  }

  private func makeClueRewritePromptPrefix() -> String {
    """
    Rewrite the clues for these crossword answers. Keep the same words, just make the clues more fun:
    preserve the answer, tighten the wording, and keep each clue fair but not obvious.
    If an answer is a verb, avoid clues that merely restate the action as a command or infinitive.
    """
  }

  // MARK: - Scoring / weighting

  /// Returns true if the clue contains the answer word or any common morphological form of it
  /// (e.g. plurals, past tense, progressive, agent nouns). Generates explicit inflected forms
  /// to catch violations like "skates" for the answer "SKATE" or "skiing" for "SKI".
  ///
  /// Limitations: irregular inflections (go→went) and consonant-doubling forms
  /// (stop→stopped, plan→planned, run→running) are not generated. These are uncommon
  /// enough that the AI prompt instruction acts as the primary guard; this check is a
  /// safety net for the most common regular inflections.
  ///
  /// Words shorter than 3 letters are checked by exact match only; the crossword engine
  /// enforces a 3-letter minimum for answers so this guard is intentionally conservative.
  static func clueContainsAnswerOrForm(_ clueWords: Set<String>, answerWord: String) -> Bool {
    if clueWords.contains(answerWord) { return true }
    guard answerWord.count >= 3 else { return false }

    var forms: Set<String> = []

    // Plural / 3rd-person singular.
    // Any word ending in a sibilant (s, x, z, sh, ch) takes +ES rather than +S, per
    // standard English: GAS→GASES, BUS→BUSES, GLASS→GLASSES, MATCH→MATCHES, etc.
    // hasSuffix("S") matches both single-S endings (GAS, BUS) and double-S (GLASS, AMASS).
    // All other words take plain +S: SKATE→SKATES, PLAY→PLAYS, SKI→SKIS.
    let esSuffixes = ["S", "X", "Z", "SH", "CH"]
    if esSuffixes.contains(where: { answerWord.hasSuffix($0) }) {
      forms.insert(answerWord + "ES")
    } else {
      forms.insert(answerWord + "S")
    }

    if answerWord.hasSuffix("E") {
      let stem = String(answerWord.dropLast())
      // Past tense: SKATE→SKATED, LOVE→LOVED
      forms.insert(stem + "ED")
      // Progressive (E-drop): SKATE→SKATING, LOVE→LOVING
      forms.insert(stem + "ING")
      // Agent noun (E-drop): SKATE→SKATER/SKATERS, LOVE→LOVER/LOVERS
      forms.insert(stem + "ER")
      forms.insert(stem + "ERS")
    } else {
      // Past tense: PLAY→PLAYED, SKI→SKIED
      forms.insert(answerWord + "ED")
      // Progressive: PLAY→PLAYING, SKI→SKIING
      forms.insert(answerWord + "ING")
      // Agent noun: PLAY→PLAYER/PLAYERS, SKI→SKIER/SKIERS
      forms.insert(answerWord + "ER")
      forms.insert(answerWord + "ERS")
    }

    // Adverb: QUICK→QUICKLY, SMART→SMARTLY.
    // Skip if the answer word already ends in LY to avoid QUICKLYLY etc.
    if !answerWord.hasSuffix("LY") {
      forms.insert(answerWord + "LY")
    }

    return !clueWords.isDisjoint(with: forms)
  }

  private func scoreCandidate(
    word: String,
    clue: String,
    recentWords: Set<String>
  ) -> Int {
    var score = 0

    if recentWords.contains(word) {
      score -= 7
    }

    if genericWords.contains(word) {
      score -= 8
    }

    if overusedModelFavorites.contains(word) {
      score -= 6
    }

    let uppercaseClue = clue.uppercased()
    if uppercaseClue.contains("SAY")
      || uppercaseClue.contains("MAYBE")
      || uppercaseClue.contains("SOMETIMES")
      || uppercaseClue.contains("FIGURATIVELY")
    {
      score += 2
    }

    let vowels = word.filter { "AEIOU".contains($0) }.count
    let consonants = word.count - vowels
    if vowels >= 1 && consonants >= 2 {
      score += 2
    }

    if word.count >= 5 {
      score += 1
    }

    return score
  }

  // MARK: - Recent words persistence

  private func loadRecentWords() -> [String] {
    UserDefaults.standard.stringArray(forKey: recentWordsKey) ?? []
  }

  private func saveRecentWords(_ words: [String]) {
    let normalized = Array(
      words
        .map { $0.uppercased() }
        .removingDuplicatesPreservingOrder()
        .suffix(recentWordsLimit)
    )
    UserDefaults.standard.set(normalized, forKey: recentWordsKey)
  }

  private func appendRecentWords(_ newWords: [String]) {
    let existing = loadRecentWords()
    saveRecentWords(existing + newWords.map { $0.uppercased() })
  }

  /// Clears the recent words history, allowing previously used words to be generated again.
  func clearRecentWords() {
    UserDefaults.standard.removeObject(forKey: recentWordsKey)
    logger.info("Cleared AI recent words history")
  }

  // MARK: - Fallback

  /// Fallback: return words from the bundled wordlist.
  private func fallbackWords(
    count: Int,
    maxLength: Int,
    seed: UInt64,
    excludedWords: Set<String> = []
  ) -> [WordClue] {
    let solvedWords = Set(persistence.loadSolvedWords())
    let all = fallbackService.entries.filter {
      $0.word.count >= 3 && $0.word.count <= maxLength
        && !WordSafetyFilter.isBlocked($0.word)
        && !solvedWords.contains($0.word.uppercased())
        && !excludedWords.contains($0.word.uppercased())
    }
    var rng = GKMersenneTwisterRandomSource(seed: seed)
    var shuffled = all
    shuffled.shuffle(using: &rng)
    return Array(shuffled.prefix(count))
  }

  /// Fallback with AI clue enhancement: uses bundled words but rewrites clues
  /// with Apple Intelligence if available. Falls back to bundled clues on failure/timeout.
  private func fallbackWithAIClues(
    count: Int,
    maxLength: Int,
    seed: UInt64,
    excludedWords: Set<String> = [],
    baseDetail: String?
  ) async -> GenerationResult {
    let words = fallbackWords(
      count: count,
      maxLength: maxLength,
      seed: seed,
      excludedWords: excludedWords
    )

    guard isAvailable else {
      return GenerationResult(
        words: words,
        aiGeneratedWords: [],
        status: .appleIntelligenceUnavailable,
        detail: baseDetail
      )
    }

    logger.info("Attempting AI clue rewrite for \(words.count) bundled words")

    do {
      let rewritten = try await withThrowingTaskGroup(of: [WordClue].self) { group in
        group.addTask {
          try await self.rewriteCluesWithAI(words: words)
        }
        group.addTask {
          try await Task.sleep(for: .seconds(Self.clueRewriteTimeoutSeconds))
          throw AITimeoutError()
        }

        if let result = try await group.next() {
          group.cancelAll()
          return result
        }
        return words
      }

      let rewrittenCount = zip(words, rewritten).filter { $0.clue != $1.clue }.count
      logger.info("AI clue rewrite complete: \(rewrittenCount)/\(words.count) clues rewritten")

      return GenerationResult(
        words: rewritten,
        aiGeneratedWords: [],
        status: .fallbackWithAIClues,
        detail: [baseDetail, "Rewrote \(rewrittenCount) clues with Apple Intelligence."]
          .compactMap { $0 }
          .joined(separator: " ")
      )
    } catch is AITimeoutError {
      logger.warning("AI clue rewrite timed out — using bundled clues")
      return GenerationResult(
        words: words,
        aiGeneratedWords: [],
        status: .validationFailed,
        detail: [baseDetail, "AI clue rewrite timed out."].compactMap { $0 }.joined(separator: " ")
      )
    } catch {
      logger.warning("AI clue rewrite failed: \(error.localizedDescription) — using bundled clues")
      return GenerationResult(
        words: words,
        aiGeneratedWords: [],
        status: .validationFailed,
        detail: [baseDetail, "AI clue rewrite failed."].compactMap { $0 }.joined(separator: " ")
      )
    }
  }

  // MARK: - AI clue rewriting

  /// Rewrites bundled wordlist clues using Apple Intelligence for a more playful style.
  private func rewriteCluesWithAI(words: [WordClue]) async throws -> [WordClue] {
    let wordList = words.map { "\($0.word) — \($0.clue)" }.joined(separator: "\n")

    let instructions = """
      You are an expert crossword clue writer. You will be given crossword answers paired with plain dictionary-style clues.
      Rewrite each clue to be clever, playful, and crossword-worthy.

      RULES:
      - Keep the exact same answer word (in UPPERCASE)
      - Write a new clue that is 2-8 words long
      - Clues must NOT contain the answer word or any form of it
      - Prefer playful, indirect, figurative, conversational, or lightly witty clues
      - For verb answers, avoid direct command-style clues and simple action sentences
      - Use mild misdirection, double meanings, or wordplay when possible
      - Clues must read as complete natural phrases, never fragments
      - Avoid plain dictionary definitions
      - Return every word you are given — do not skip any
      """

    let session = LanguageModelSession(instructions: instructions)

    let prompt = """
      \(makeClueRewritePromptPrefix())

      \(wordList)
      """

    let response = try await session.respond(
      to: prompt,
      generating: RewrittenClueBatch.self,
      includeSchemaInPrompt: false,
      options: GenerationOptions(sampling: .greedy)
    )

    // Build a lookup from the AI response
    var rewrittenClues: [String: String] = [:]
    for entry in response.content.entries {
      let word = entry.word.uppercased().trimmingCharacters(in: .whitespacesAndNewlines)
      let clue = entry.clue.trimmingCharacters(in: .whitespacesAndNewlines)

      guard !clue.isEmpty else { continue }

      // Validate: clue must not contain the answer word
      let clueWords = Set(
        clue.uppercased()
          .components(separatedBy: .whitespacesAndNewlines)
          .map { $0.trimmingCharacters(in: .punctuationCharacters) }
          .filter { !$0.isEmpty }
      )
      guard !Self.clueContainsAnswerOrForm(clueWords, answerWord: word) else { continue }

      // Check for incomplete clue endings
      let lastWord =
        clue
        .components(separatedBy: .whitespacesAndNewlines)
        .last?
        .lowercased()
        .trimmingCharacters(in: .punctuationCharacters) ?? ""
      guard !Self.incompleteClueEnders.contains(lastWord) else { continue }

      rewrittenClues[word] = clue
    }

    // Merge: use AI clue if available, otherwise keep bundled clue
    return words.map { original in
      if let aiClue = rewrittenClues[original.word] {
        return WordClue(word: original.word, clue: aiClue)
      }
      return original
    }
  }
}

// MARK: - Helpers

extension Array where Element: Hashable {
  fileprivate func removingDuplicatesPreservingOrder() -> [Element] {
    var seen = Set<Element>()
    return filter { seen.insert($0).inserted }
  }
}
