import Foundation

/// Indicates whether a word's clue was generated by AI or came from the bundled list.
enum WordSource: String, Codable, Sendable, Equatable {
    case ai
    case bundled
}

/// A word placed in the puzzle grid, along with its clue.
struct WordEntry: Codable, Identifiable, Sendable, Equatable {
    let id: UUID
    let direction: WordDirection
    let text: String
    let clue: String
    let startRow: Int
    let startCol: Int
    let source: WordSource

    /// Number of letters in the word.
    var length: Int { text.count }

    /// The grid positions this word occupies, in order.
    var cells: [(row: Int, col: Int)] {
        (0..<length).map { offset in
            switch direction {
            case .across:
                return (row: startRow, col: startCol + offset)
            case .down:
                return (row: startRow + offset, col: startCol)
            }
        }
    }

    init(
        id: UUID = UUID(),
        direction: WordDirection,
        text: String,
        clue: String,
        startRow: Int,
        startCol: Int,
        source: WordSource = .bundled
    ) {
        self.id = id
        self.direction = direction
        self.text = text
        self.clue = clue
        self.startRow = startRow
        self.startCol = startCol
        self.source = source
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        direction = try container.decode(WordDirection.self, forKey: .direction)
        text = try container.decode(String.self, forKey: .text)
        clue = try container.decode(String.self, forKey: .clue)
        startRow = try container.decode(Int.self, forKey: .startRow)
        startCol = try container.decode(Int.self, forKey: .startCol)
        source = try container.decodeIfPresent(WordSource.self, forKey: .source) ?? .bundled
    }
}
